language: python
addons:
  firefox: latest
python:
  - "3.7"
#Command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - xvfb
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script:
  - coverage run manage.py test
after_success:
  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: "1e0962c3-7aa6-4253-b297-834a83837ae7"
  app: sr-tdd-tutorial
    
